// This file is auto-generated by @hey-api/openapi-ts

import { type Options, deleteConfig, getCurrentConfig, updateConfig, listConfigs, resetConfig, createConfig, switchConfig, getConfigSchema, getConfigUiSchema, getDefaultConfig, getWebSocketConnections, listFiles, startScrape, scrapeSingleFile, createSymlink, addSubtitles, getActors, completeActors, checkCookies, getSiteUrls, setSiteUrl, getScrapeResults, getScrapeStatus, stopScrape, getPendingAsks, answerAsk, getSuccessList, saveSuccessList, clearSuccessList, getFailedList, retryFailedList, checkMissingNumbers, cleanFiles, moveVideos, manageExtras, manageExtrafanartCopy, manageThemeVideos, manageKodiActors, listActors, checkCookie, getPosterInfo, getPosterImage, cutPoster } from '../sdk.gen';
import { type UseMutationOptions, queryOptions, type DefaultError } from '@tanstack/react-query';
import type { DeleteConfigData, DeleteConfigError, GetCurrentConfigData, UpdateConfigData, UpdateConfigError, UpdateConfigResponse, ListConfigsData, ResetConfigData, ResetConfigResponse, CreateConfigData, CreateConfigError, SwitchConfigData, SwitchConfigError, SwitchConfigResponse, GetConfigSchemaData, GetConfigUiSchemaData, GetDefaultConfigData, GetWebSocketConnectionsData, ListFilesData, StartScrapeData, ScrapeSingleFileData, ScrapeSingleFileError, CreateSymlinkData, CreateSymlinkError, AddSubtitlesData, GetActorsData, CompleteActorsData, CheckCookiesData, GetSiteUrlsData, SetSiteUrlData, SetSiteUrlError, GetScrapeResultsData, GetScrapeStatusData, StopScrapeData, StopScrapeResponse, GetPendingAsksData, AnswerAskData, AnswerAskError, AnswerAskResponse, GetSuccessListData, SaveSuccessListData, SaveSuccessListResponse, ClearSuccessListData, ClearSuccessListResponse, GetFailedListData, RetryFailedListData, RetryFailedListResponse, CheckMissingNumbersData, CheckMissingNumbersResponse, CleanFilesData, CleanFilesResponse, MoveVideosData, MoveVideosResponse, ManageExtrasData, ManageExtrasError, ManageExtrasResponse, ManageExtrafanartCopyData, ManageExtrafanartCopyError, ManageExtrafanartCopyResponse, ManageThemeVideosData, ManageThemeVideosError, ManageThemeVideosResponse, ManageKodiActorsData, ManageKodiActorsError, ManageKodiActorsResponse, ListActorsData, ListActorsError, ListActorsResponse, CheckCookieData, CheckCookieError, CheckCookieResponse, GetPosterInfoData, GetPosterImageData, CutPosterData, CutPosterError, CutPosterResponse } from '../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';

/**
 * 删除配置文件
 */
export const deleteConfigMutation = (options?: Partial<Options<DeleteConfigData>>): UseMutationOptions<unknown, AxiosError<DeleteConfigError>, Options<DeleteConfigData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DeleteConfigError>, Options<DeleteConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getCurrentConfigQueryKey = (options?: Options<GetCurrentConfigData>) => createQueryKey('getCurrentConfig', options);

/**
 * 获取当前配置
 */
export const getCurrentConfigOptions = (options?: Options<GetCurrentConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCurrentConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCurrentConfigQueryKey(options)
    });
};

/**
 * 更新配置
 */
export const updateConfigMutation = (options?: Partial<Options<UpdateConfigData>>): UseMutationOptions<UpdateConfigResponse, AxiosError<UpdateConfigError>, Options<UpdateConfigData>> => {
    const mutationOptions: UseMutationOptions<UpdateConfigResponse, AxiosError<UpdateConfigError>, Options<UpdateConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await updateConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listConfigsQueryKey = (options?: Options<ListConfigsData>) => createQueryKey('listConfigs', options);

/**
 * 列出配置文件
 * 返回配置文件夹中的所有配置文件名与当前激活的配置名.
 */
export const listConfigsOptions = (options?: Options<ListConfigsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listConfigs({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listConfigsQueryKey(options)
    });
};

export const resetConfigQueryKey = (options?: Options<ResetConfigData>) => createQueryKey('resetConfig', options);

/**
 * 重置配置
 * 将当前配置重置为默认值
 */
export const resetConfigOptions = (options?: Options<ResetConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await resetConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: resetConfigQueryKey(options)
    });
};

/**
 * 重置配置
 * 将当前配置重置为默认值
 */
export const resetConfigMutation = (options?: Partial<Options<ResetConfigData>>): UseMutationOptions<ResetConfigResponse, AxiosError<DefaultError>, Options<ResetConfigData>> => {
    const mutationOptions: UseMutationOptions<ResetConfigResponse, AxiosError<DefaultError>, Options<ResetConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await resetConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createConfigQueryKey = (options: Options<CreateConfigData>) => createQueryKey('createConfig', options);

/**
 * 创建配置文件
 * 创建指定名称的配置文件, 内容为默认配置
 */
export const createConfigOptions = (options: Options<CreateConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createConfigQueryKey(options)
    });
};

/**
 * 创建配置文件
 * 创建指定名称的配置文件, 内容为默认配置
 */
export const createConfigMutation = (options?: Partial<Options<CreateConfigData>>): UseMutationOptions<unknown, AxiosError<CreateConfigError>, Options<CreateConfigData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CreateConfigError>, Options<CreateConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const switchConfigQueryKey = (options: Options<SwitchConfigData>) => createQueryKey('switchConfig', options);

/**
 * 切换配置
 * 切换到现有的配置文件。
 */
export const switchConfigOptions = (options: Options<SwitchConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await switchConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: switchConfigQueryKey(options)
    });
};

/**
 * 切换配置
 * 切换到现有的配置文件。
 */
export const switchConfigMutation = (options?: Partial<Options<SwitchConfigData>>): UseMutationOptions<SwitchConfigResponse, AxiosError<SwitchConfigError>, Options<SwitchConfigData>> => {
    const mutationOptions: UseMutationOptions<SwitchConfigResponse, AxiosError<SwitchConfigError>, Options<SwitchConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await switchConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getConfigSchemaQueryKey = (options?: Options<GetConfigSchemaData>) => createQueryKey('getConfigSchema', options);

/**
 * 获取配置架构
 * 返回配置的JSON架构。
 */
export const getConfigSchemaOptions = (options?: Options<GetConfigSchemaData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getConfigSchema({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getConfigSchemaQueryKey(options)
    });
};

export const getConfigUiSchemaQueryKey = (options?: Options<GetConfigUiSchemaData>) => createQueryKey('getConfigUiSchema', options);

/**
 * 获取UI架构
 * 返回配置的UI架构。
 */
export const getConfigUiSchemaOptions = (options?: Options<GetConfigUiSchemaData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getConfigUiSchema({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getConfigUiSchemaQueryKey(options)
    });
};

export const getDefaultConfigQueryKey = (options?: Options<GetDefaultConfigData>) => createQueryKey('getDefaultConfig', options);

/**
 * 获取默认配置
 * 返回默认配置。
 */
export const getDefaultConfigOptions = (options?: Options<GetDefaultConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDefaultConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDefaultConfigQueryKey(options)
    });
};

export const getWebSocketConnectionsQueryKey = (options?: Options<GetWebSocketConnectionsData>) => createQueryKey('getWebSocketConnections', options);

/**
 * 获取所有 WebSocket 连接信息
 */
export const getWebSocketConnectionsOptions = (options?: Options<GetWebSocketConnectionsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getWebSocketConnections({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWebSocketConnectionsQueryKey(options)
    });
};

export const listFilesQueryKey = (options: Options<ListFilesData>) => createQueryKey('listFiles', options);

/**
 * 列出文件和目录
 * 列出指定路径下的文件和目录. 仅允许访问 `SAFE_DIRS` 目录下的内容, `SAFE_DIRS` 可通过服务器环境变量 `MDCX_SAFE_DIRS` 设置. 指向 `SAFE_DIRS` 外目录的软链接本身可见, 但无法访问其内容.
 */
export const listFilesOptions = (options: Options<ListFilesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listFiles({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listFilesQueryKey(options)
    });
};

export const startScrapeQueryKey = (options?: Options<StartScrapeData>) => createQueryKey('startScrape', options);

/**
 * 开始刮削
 * 使用当前配置运行刮削流程, 无需额外参数
 */
export const startScrapeOptions = (options?: Options<StartScrapeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await startScrape({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: startScrapeQueryKey(options)
    });
};

/**
 * 开始刮削
 * 使用当前配置运行刮削流程, 无需额外参数
 */
export const startScrapeMutation = (options?: Partial<Options<StartScrapeData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<StartScrapeData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<StartScrapeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await startScrape({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const scrapeSingleFileQueryKey = (options: Options<ScrapeSingleFileData>) => createQueryKey('scrapeSingleFile', options);

/**
 * 单文件刮削
 */
export const scrapeSingleFileOptions = (options: Options<ScrapeSingleFileData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await scrapeSingleFile({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: scrapeSingleFileQueryKey(options)
    });
};

/**
 * 单文件刮削
 */
export const scrapeSingleFileMutation = (options?: Partial<Options<ScrapeSingleFileData>>): UseMutationOptions<unknown, AxiosError<ScrapeSingleFileError>, Options<ScrapeSingleFileData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<ScrapeSingleFileError>, Options<ScrapeSingleFileData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await scrapeSingleFile({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createSymlinkQueryKey = (options: Options<CreateSymlinkData>) => createQueryKey('createSymlink', options);

/**
 * 创建软链接
 */
export const createSymlinkOptions = (options: Options<CreateSymlinkData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createSymlink({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createSymlinkQueryKey(options)
    });
};

/**
 * 创建软链接
 */
export const createSymlinkMutation = (options?: Partial<Options<CreateSymlinkData>>): UseMutationOptions<unknown, AxiosError<CreateSymlinkError>, Options<CreateSymlinkData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CreateSymlinkError>, Options<CreateSymlinkData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createSymlink({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const addSubtitlesQueryKey = (options?: Options<AddSubtitlesData>) => createQueryKey('addSubtitles', options);

/**
 * 检查并添加字幕
 * 检查媒体库字幕情况并自动添加 (依据本地字幕包)
 */
export const addSubtitlesOptions = (options?: Options<AddSubtitlesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await addSubtitles({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addSubtitlesQueryKey(options)
    });
};

/**
 * 检查并添加字幕
 * 检查媒体库字幕情况并自动添加 (依据本地字幕包)
 */
export const addSubtitlesMutation = (options?: Partial<Options<AddSubtitlesData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AddSubtitlesData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AddSubtitlesData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await addSubtitles({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getActorsQueryKey = (options?: Options<GetActorsData>) => createQueryKey('getActors', options);

/**
 * 查看媒体服务器演员名单
 * 查看 emby/jellyfin 中符合条件的演员名单
 */
export const getActorsOptions = (options?: Options<GetActorsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getActors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getActorsQueryKey(options)
    });
};

export const completeActorsQueryKey = (options?: Options<CompleteActorsData>) => createQueryKey('completeActors', options);

/**
 * 补全演员信息
 * 补全 emby/jellyfin 演员信息/头像
 */
export const completeActorsOptions = (options?: Options<CompleteActorsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await completeActors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: completeActorsQueryKey(options)
    });
};

/**
 * 补全演员信息
 * 补全 emby/jellyfin 演员信息/头像
 */
export const completeActorsMutation = (options?: Partial<Options<CompleteActorsData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CompleteActorsData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CompleteActorsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await completeActors({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const checkCookiesQueryKey = (options?: Options<CheckCookiesData>) => createQueryKey('checkCookies', options);

/**
 * Cookie 有效性检查
 */
export const checkCookiesOptions = (options?: Options<CheckCookiesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await checkCookies({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: checkCookiesQueryKey(options)
    });
};

/**
 * Cookie 有效性检查
 */
export const checkCookiesMutation = (options?: Partial<Options<CheckCookiesData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CheckCookiesData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CheckCookiesData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await checkCookies({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSiteUrlsQueryKey = (options?: Options<GetSiteUrlsData>) => createQueryKey('getSiteUrls', options);

/**
 * 获取网站自定义网址
 * 获取网站自定义网址设置.
 */
export const getSiteUrlsOptions = (options?: Options<GetSiteUrlsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSiteUrls({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSiteUrlsQueryKey(options)
    });
};

export const setSiteUrlQueryKey = (options: Options<SetSiteUrlData>) => createQueryKey('setSiteUrl', options);

/**
 * 设置网站自定义网址
 * 指定网站自定义网址设置
 */
export const setSiteUrlOptions = (options: Options<SetSiteUrlData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await setSiteUrl({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: setSiteUrlQueryKey(options)
    });
};

/**
 * 设置网站自定义网址
 * 指定网站自定义网址设置
 */
export const setSiteUrlMutation = (options?: Partial<Options<SetSiteUrlData>>): UseMutationOptions<unknown, AxiosError<SetSiteUrlError>, Options<SetSiteUrlData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<SetSiteUrlError>, Options<SetSiteUrlData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await setSiteUrl({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getScrapeResultsQueryKey = (options?: Options<GetScrapeResultsData>) => createQueryKey('getScrapeResults', options);

/**
 * 获取刮削结果明细
 * 返回服务端留存的结果明细, 页面加载时用它补回错过的 WebSocket 推送.
 */
export const getScrapeResultsOptions = (options?: Options<GetScrapeResultsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getScrapeResults({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getScrapeResultsQueryKey(options)
    });
};

export const getScrapeStatusQueryKey = (options?: Options<GetScrapeStatusData>) => createQueryKey('getScrapeStatus', options);

/**
 * 获取刮削状态
 * 返回当前刮削进度与统计.
 */
export const getScrapeStatusOptions = (options?: Options<GetScrapeStatusData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getScrapeStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getScrapeStatusQueryKey(options)
    });
};

export const stopScrapeQueryKey = (options?: Options<StopScrapeData>) => createQueryKey('stopScrape', options);

/**
 * 停止刮削
 * 停止正在进行的刮削.
 *
 * 与桌面版行为一致: 先保存已成功列表, 再取消后台任务.
 */
export const stopScrapeOptions = (options?: Options<StopScrapeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await stopScrape({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: stopScrapeQueryKey(options)
    });
};

/**
 * 停止刮削
 * 停止正在进行的刮削.
 *
 * 与桌面版行为一致: 先保存已成功列表, 再取消后台任务.
 */
export const stopScrapeMutation = (options?: Partial<Options<StopScrapeData>>): UseMutationOptions<StopScrapeResponse, AxiosError<DefaultError>, Options<StopScrapeData>> => {
    const mutationOptions: UseMutationOptions<StopScrapeResponse, AxiosError<DefaultError>, Options<StopScrapeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await stopScrape({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPendingAsksQueryKey = (options?: Options<GetPendingAsksData>) => createQueryKey('getPendingAsks', options);

/**
 * 获取待回答的问题
 * 列出所有等待回答的问题.
 *
 * 页面刷新或重连后调用此接口, 可以恢复错过的提问对话框.
 */
export const getPendingAsksOptions = (options?: Options<GetPendingAsksData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPendingAsks({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPendingAsksQueryKey(options)
    });
};

export const answerAskQueryKey = (options: Options<AnswerAskData>) => createQueryKey('answerAsk', options);

/**
 * 回答问题
 * 提交某个问题的答案, 唤醒等待中的后台任务.
 */
export const answerAskOptions = (options: Options<AnswerAskData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await answerAsk({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: answerAskQueryKey(options)
    });
};

/**
 * 回答问题
 * 提交某个问题的答案, 唤醒等待中的后台任务.
 */
export const answerAskMutation = (options?: Partial<Options<AnswerAskData>>): UseMutationOptions<AnswerAskResponse, AxiosError<AnswerAskError>, Options<AnswerAskData>> => {
    const mutationOptions: UseMutationOptions<AnswerAskResponse, AxiosError<AnswerAskError>, Options<AnswerAskData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await answerAsk({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSuccessListQueryKey = (options?: Options<GetSuccessListData>) => createQueryKey('getSuccessList', options);

/**
 * 获取已成功刮削的文件列表
 * 返回本次运行期间已成功刮削的文件, 用于日志页展示与导出.
 */
export const getSuccessListOptions = (options?: Options<GetSuccessListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSuccessList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSuccessListQueryKey(options)
    });
};

export const saveSuccessListQueryKey = (options?: Options<SaveSuccessListData>) => createQueryKey('saveSuccessList', options);

/**
 * 保存成功列表
 * 把当前成功列表落盘到 success.txt.
 *
 * 刮削过程中会自动定期保存, 这个接口供用户手动确认保存一次.
 */
export const saveSuccessListOptions = (options?: Options<SaveSuccessListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await saveSuccessList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: saveSuccessListQueryKey(options)
    });
};

/**
 * 保存成功列表
 * 把当前成功列表落盘到 success.txt.
 *
 * 刮削过程中会自动定期保存, 这个接口供用户手动确认保存一次.
 */
export const saveSuccessListMutation = (options?: Partial<Options<SaveSuccessListData>>): UseMutationOptions<SaveSuccessListResponse, AxiosError<DefaultError>, Options<SaveSuccessListData>> => {
    const mutationOptions: UseMutationOptions<SaveSuccessListResponse, AxiosError<DefaultError>, Options<SaveSuccessListData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await saveSuccessList({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const clearSuccessListQueryKey = (options?: Options<ClearSuccessListData>) => createQueryKey('clearSuccessList', options);

/**
 * 清空成功列表
 * 清空成功列表并同步落盘.
 *
 * 清空后这些文件会被视为未刮削, 下次扫描时会重新处理.
 */
export const clearSuccessListOptions = (options?: Options<ClearSuccessListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await clearSuccessList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: clearSuccessListQueryKey(options)
    });
};

/**
 * 清空成功列表
 * 清空成功列表并同步落盘.
 *
 * 清空后这些文件会被视为未刮削, 下次扫描时会重新处理.
 */
export const clearSuccessListMutation = (options?: Partial<Options<ClearSuccessListData>>): UseMutationOptions<ClearSuccessListResponse, AxiosError<DefaultError>, Options<ClearSuccessListData>> => {
    const mutationOptions: UseMutationOptions<ClearSuccessListResponse, AxiosError<DefaultError>, Options<ClearSuccessListData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await clearSuccessList({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getFailedListQueryKey = (options?: Options<GetFailedListData>) => createQueryKey('getFailedList', options);

/**
 * 获取失败文件列表
 * 返回本次刮削中失败的文件及原因.
 */
export const getFailedListOptions = (options?: Options<GetFailedListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getFailedList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getFailedListQueryKey(options)
    });
};

export const retryFailedListQueryKey = (options?: Options<RetryFailedListData>) => createQueryKey('retryFailedList', options);

/**
 * 重新刮削失败列表
 * 用当前失败列表作为待刮削清单, 重新跑一遍.
 */
export const retryFailedListOptions = (options?: Options<RetryFailedListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await retryFailedList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: retryFailedListQueryKey(options)
    });
};

/**
 * 重新刮削失败列表
 * 用当前失败列表作为待刮削清单, 重新跑一遍.
 */
export const retryFailedListMutation = (options?: Partial<Options<RetryFailedListData>>): UseMutationOptions<RetryFailedListResponse, AxiosError<DefaultError>, Options<RetryFailedListData>> => {
    const mutationOptions: UseMutationOptions<RetryFailedListResponse, AxiosError<DefaultError>, Options<RetryFailedListData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await retryFailedList({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const checkMissingNumbersQueryKey = (options?: Options<CheckMissingNumbersData>) => createQueryKey('checkMissingNumbers', options);

/**
 * 检查缺失番号
 * 按演员作品列表比对本地库, 找出缺失的番号 (需在设置中配置本地库与演员).
 */
export const checkMissingNumbersOptions = (options?: Options<CheckMissingNumbersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await checkMissingNumbers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: checkMissingNumbersQueryKey(options)
    });
};

/**
 * 检查缺失番号
 * 按演员作品列表比对本地库, 找出缺失的番号 (需在设置中配置本地库与演员).
 */
export const checkMissingNumbersMutation = (options?: Partial<Options<CheckMissingNumbersData>>): UseMutationOptions<CheckMissingNumbersResponse, AxiosError<DefaultError>, Options<CheckMissingNumbersData>> => {
    const mutationOptions: UseMutationOptions<CheckMissingNumbersResponse, AxiosError<DefaultError>, Options<CheckMissingNumbersData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await checkMissingNumbers({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const cleanFilesQueryKey = (options?: Options<CleanFilesData>) => createQueryKey('cleanFiles', options);

/**
 * 检查并清理文件
 * 清理媒体目录中的空目录与残留文件.
 *
 * 需要在设置中同时勾选清理功能的两项确认开关, 否则拒绝执行 —— 这是原版的
 * 安全设计, 避免误删.
 */
export const cleanFilesOptions = (options?: Options<CleanFilesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await cleanFiles({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: cleanFilesQueryKey(options)
    });
};

/**
 * 检查并清理文件
 * 清理媒体目录中的空目录与残留文件.
 *
 * 需要在设置中同时勾选清理功能的两项确认开关, 否则拒绝执行 —— 这是原版的
 * 安全设计, 避免误删.
 */
export const cleanFilesMutation = (options?: Partial<Options<CleanFilesData>>): UseMutationOptions<CleanFilesResponse, AxiosError<DefaultError>, Options<CleanFilesData>> => {
    const mutationOptions: UseMutationOptions<CleanFilesResponse, AxiosError<DefaultError>, Options<CleanFilesData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await cleanFiles({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const moveVideosQueryKey = (options?: Options<MoveVideosData>) => createQueryKey('moveVideos', options);

/**
 * 移动视频和字幕
 * 把媒体目录下的视频与字幕移动到底下的 Movie_moved 子目录.
 */
export const moveVideosOptions = (options?: Options<MoveVideosData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await moveVideos({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: moveVideosQueryKey(options)
    });
};

/**
 * 移动视频和字幕
 * 把媒体目录下的视频与字幕移动到底下的 Movie_moved 子目录.
 */
export const moveVideosMutation = (options?: Partial<Options<MoveVideosData>>): UseMutationOptions<MoveVideosResponse, AxiosError<DefaultError>, Options<MoveVideosData>> => {
    const mutationOptions: UseMutationOptions<MoveVideosResponse, AxiosError<DefaultError>, Options<MoveVideosData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await moveVideos({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const manageExtrasQueryKey = (options: Options<ManageExtrasData>) => createQueryKey('manageExtras', options);

/**
 * 批量添加/删除剧照
 * 为媒体库中所有影片批量添加或删除 extras 剧照.
 */
export const manageExtrasOptions = (options: Options<ManageExtrasData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await manageExtras({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: manageExtrasQueryKey(options)
    });
};

/**
 * 批量添加/删除剧照
 * 为媒体库中所有影片批量添加或删除 extras 剧照.
 */
export const manageExtrasMutation = (options?: Partial<Options<ManageExtrasData>>): UseMutationOptions<ManageExtrasResponse, AxiosError<ManageExtrasError>, Options<ManageExtrasData>> => {
    const mutationOptions: UseMutationOptions<ManageExtrasResponse, AxiosError<ManageExtrasError>, Options<ManageExtrasData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await manageExtras({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const manageExtrafanartCopyQueryKey = (options: Options<ManageExtrafanartCopyData>) => createQueryKey('manageExtrafanartCopy', options);

/**
 * 批量添加/删除剧照副本
 * 把剧照复制到独立目录供 Emby 使用, 或删除这些副本.
 */
export const manageExtrafanartCopyOptions = (options: Options<ManageExtrafanartCopyData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await manageExtrafanartCopy({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: manageExtrafanartCopyQueryKey(options)
    });
};

/**
 * 批量添加/删除剧照副本
 * 把剧照复制到独立目录供 Emby 使用, 或删除这些副本.
 */
export const manageExtrafanartCopyMutation = (options?: Partial<Options<ManageExtrafanartCopyData>>): UseMutationOptions<ManageExtrafanartCopyResponse, AxiosError<ManageExtrafanartCopyError>, Options<ManageExtrafanartCopyData>> => {
    const mutationOptions: UseMutationOptions<ManageExtrafanartCopyResponse, AxiosError<ManageExtrafanartCopyError>, Options<ManageExtrafanartCopyData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await manageExtrafanartCopy({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const manageThemeVideosQueryKey = (options: Options<ManageThemeVideosData>) => createQueryKey('manageThemeVideos', options);

/**
 * 批量添加/删除主题视频
 * 为媒体库中所有影片批量添加或删除主题视频.
 */
export const manageThemeVideosOptions = (options: Options<ManageThemeVideosData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await manageThemeVideos({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: manageThemeVideosQueryKey(options)
    });
};

/**
 * 批量添加/删除主题视频
 * 为媒体库中所有影片批量添加或删除主题视频.
 */
export const manageThemeVideosMutation = (options?: Partial<Options<ManageThemeVideosData>>): UseMutationOptions<ManageThemeVideosResponse, AxiosError<ManageThemeVideosError>, Options<ManageThemeVideosData>> => {
    const mutationOptions: UseMutationOptions<ManageThemeVideosResponse, AxiosError<ManageThemeVideosError>, Options<ManageThemeVideosData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await manageThemeVideos({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const manageKodiActorsQueryKey = (options: Options<ManageKodiActorsData>) => createQueryKey('manageKodiActors', options);

/**
 * 创建/删除 Kodi 演员文件夹
 * 为待刮削目录中的每个视频创建或删除 .actors 文件夹 (Kodi 风格的演员图目录).
 */
export const manageKodiActorsOptions = (options: Options<ManageKodiActorsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await manageKodiActors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: manageKodiActorsQueryKey(options)
    });
};

/**
 * 创建/删除 Kodi 演员文件夹
 * 为待刮削目录中的每个视频创建或删除 .actors 文件夹 (Kodi 风格的演员图目录).
 */
export const manageKodiActorsMutation = (options?: Partial<Options<ManageKodiActorsData>>): UseMutationOptions<ManageKodiActorsResponse, AxiosError<ManageKodiActorsError>, Options<ManageKodiActorsData>> => {
    const mutationOptions: UseMutationOptions<ManageKodiActorsResponse, AxiosError<ManageKodiActorsError>, Options<ManageKodiActorsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await manageKodiActors({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listActorsQueryKey = (options: Options<ListActorsData>) => createQueryKey('listActors', options);

/**
 * 查看媒体服务器演员名单
 * 按筛选模式列出 Emby/Jellyfin 中的演员, 结果输出到日志页.
 *
 * mode 对应桌面版下拉框的九种筛选: 0 为全部演员, 1 为有信息且有头像的演员, 依此类推.
 */
export const listActorsOptions = (options: Options<ListActorsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listActors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listActorsQueryKey(options)
    });
};

/**
 * 查看媒体服务器演员名单
 * 按筛选模式列出 Emby/Jellyfin 中的演员, 结果输出到日志页.
 *
 * mode 对应桌面版下拉框的九种筛选: 0 为全部演员, 1 为有信息且有头像的演员, 依此类推.
 */
export const listActorsMutation = (options?: Partial<Options<ListActorsData>>): UseMutationOptions<ListActorsResponse, AxiosError<ListActorsError>, Options<ListActorsData>> => {
    const mutationOptions: UseMutationOptions<ListActorsResponse, AxiosError<ListActorsError>, Options<ListActorsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await listActors({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const checkCookieQueryKey = (options: Options<CheckCookieData>) => createQueryKey('checkCookie', options);

/**
 * 检测 Cookie 有效性
 * 用配置里保存的 Cookie 访问测试页面, 判断其是否仍然有效.
 *
 * 与桌面版不同的是: 这里不会自动清空失效的 Cookie, 只如实报告结果,
 * 改动配置始终由用户在设置页完成.
 */
export const checkCookieOptions = (options: Options<CheckCookieData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await checkCookie({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: checkCookieQueryKey(options)
    });
};

/**
 * 检测 Cookie 有效性
 * 用配置里保存的 Cookie 访问测试页面, 判断其是否仍然有效.
 *
 * 与桌面版不同的是: 这里不会自动清空失效的 Cookie, 只如实报告结果,
 * 改动配置始终由用户在设置页完成.
 */
export const checkCookieMutation = (options?: Partial<Options<CheckCookieData>>): UseMutationOptions<CheckCookieResponse, AxiosError<CheckCookieError>, Options<CheckCookieData>> => {
    const mutationOptions: UseMutationOptions<CheckCookieResponse, AxiosError<CheckCookieError>, Options<CheckCookieData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await checkCookie({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPosterInfoQueryKey = (options: Options<GetPosterInfoData>) => createQueryKey('getPosterInfo', options);

/**
 * 获取封面裁剪所需信息
 * 返回图片尺寸、推导出的输出路径, 以及从番号信息中预判的水印选项.
 *
 * 前端据此初始化裁剪框: 尺寸用于等比缩放与坐标换算, 水印字段用于预勾选复选框.
 */
export const getPosterInfoOptions = (options: Options<GetPosterInfoData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPosterInfo({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPosterInfoQueryKey(options)
    });
};

export const getPosterImageQueryKey = (options: Options<GetPosterImageData>) => createQueryKey('getPosterImage', options);

/**
 * 读取封面原图
 * 返回图片二进制.
 *
 * 前端需要用 fetch 取回再转成 blob URL —— img 标签无法携带 X-API-KEY 请求头,
 * 直接写 src 会在开启认证时拿到 401.
 */
export const getPosterImageOptions = (options: Options<GetPosterImageData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPosterImage({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPosterImageQueryKey(options)
    });
};

export const cutPosterQueryKey = (options: Options<CutPosterData>) => createQueryKey('cutPoster', options);

/**
 * 裁剪封面
 * 按给定矩形裁剪封面并写回.
 *
 * poster 会被裁剪替换, thumb 与 fanart 保留原图, 与桌面版裁剪窗口的行为一致.
 */
export const cutPosterOptions = (options: Options<CutPosterData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await cutPoster({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: cutPosterQueryKey(options)
    });
};

/**
 * 裁剪封面
 * 按给定矩形裁剪封面并写回.
 *
 * poster 会被裁剪替换, thumb 与 fanart 保留原图, 与桌面版裁剪窗口的行为一致.
 */
export const cutPosterMutation = (options?: Partial<Options<CutPosterData>>): UseMutationOptions<CutPosterResponse, AxiosError<CutPosterError>, Options<CutPosterData>> => {
    const mutationOptions: UseMutationOptions<CutPosterResponse, AxiosError<CutPosterError>, Options<CutPosterData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await cutPoster({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};